- name: Publish Roblox Place
  # You may pin to the exact commit or the version.
  # uses: filiptibell/roblox-place-publish-action@d58ccc461ab76576728c3262590efa9f8279037e
  uses: filiptibell/roblox-place-publish-action@v2.1
  with:
    # The universe id of the place to publish
    universe-id: # default is -1
    # The place id of the place to publish
    place-id: # default is -1
    # The Open Cloud API key with permissions to publish the place
    api-key: # default is 
    # The path to the place file to publish
    path: # default is place.rbxl
    # The maximum number of times to try to publish before failing
    max-retries: # optional, default is 3

